services:
  app:
    image: mysociety/motion-cluster-analysis:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/motion_cluster_analysis      
    volumes:
      - ./:/workspaces/motion_cluster_analysis/